export const cars = [
  {
    id: 1,
    category: "Économique",
    brand: "Renault",
    model: "Clio",
    year: 2022,
    seats: 5,
    doors: 5,
    transmission: "Manuelle",
    fuel: "Essence",
    price: 39,
    pricePerDay: 39,
    image: "/images/renault_clio.jpeg",
    options: ["GPS", "Sièges enfants"],
    promo: "10% off",
  },
  {
    id: 2,
    category: "SUV",
    brand: "Peugeot",
    model: "3008",
    year: 2023,
    seats: 5,
    doors: 5,
    transmission: "Automatique",
    fuel: "Diesel",
    price: 59,
    pricePerDay: 59,
    image: "/images/car-3008.jpeg",
    options: ["GPS"],
  },
  {
    id: 3,
    category: "Luxe",
    brand: "BMW",
    model: "Série 3",
    year: 2023,
    seats: 5,
    doors: 4,
    transmission: "Automatique",
    fuel: "Hybride",
    price: 89,
    pricePerDay: 89,
    image: "/images/car-bmw.jpeg",
    options: ["GPS", "Conduite illimitée"],
    promo: "5% off",
  },
  {
  id: 5,
  category: "Économique",
  brand: "Toyota",
  model: "Yaris",
  year: 2022,
  seats: 5,
  doors: 5,
  transmission: "Manuelle",
  fuel: "Essence",
  price: 35,
  pricePerDay: 35,
  image: "/images/car-toyota-yaris.jpeg",
  options: ["Airbag", "Climatisation"],
  promo: null,
},
{
  id: 6,
  category: "SUV",
  brand: "Volkswagen",
  model: "Tiguan",
  year: 2023,
  seats: 5,
  doors: 5,
  transmission: "Automatique",
  fuel: "Diesel",
  price: 75,
  pricePerDay: 75,
  image: "/images/car-vw-tiguan.jpeg",
  options: ["GPS", "Toit panoramique", "Sièges chauffants"],
  promo: "10% off",
},
];
